apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-deployment
  namespace: sage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: alertmanager-config-volume
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
      volumes:
        - name: alertmanager-config-volume
          configMap:
            name: alertmanager-config

---
kind: Service
apiVersion: v1
metadata:
  name: alertmanager-service
  namespace: sage
spec:
  selector:
    app: alertmanager
  ports:
  - protocol: TCP
    port: 9093
    targetPort: 9093