apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: grafana-deployment
  name: grafana-deployment
  namespace: sage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
    spec:
      # hostAliases:
      # - ip: "192.168.64.1"
      #   hostnames:
      #   - "host.minikube.internal"
      containers:
      - image: grafana/grafana
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: grafana-config-volume
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: grafana-prov-dashboards-volume
          mountPath: /etc/grafana/provisioning/dashboards
          # mountPath: /usr/share/grafana/provisioning/dashboards
        - name: grafana-prov-datasources-volume
          mountPath: /etc/grafana/provisioning/datasources

      volumes:
      - name: grafana-config-volume
        configMap:
          name: grafana-config
      - name: grafana-prov-dashboards-volume
        configMap: 
          name: grafana-prov-dashboards
      - name: grafana-prov-datasources-volume
        configMap: 
          name: grafana-prov-datasources   

---
kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  namespace: sage
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    # nodePort: 30910
  selector:
    app: grafana
  type: NodePort