{
 "title": "Data Loader Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_id",
    "query": "label_values(dataloader_message_counter_total, node_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Rate of Message Counter",
   "type": "graph",
   "description": "Per-second rate of message counters measured over the last hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate( dataloader_message_counter_total{node_id=\"$node_id\"} [1h] )"
    }
   ]
  },
  {
   "title": "Average Rate of Error Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate( dataloader_error_counter_total{node_id=\"$node_id\"} [1h] )"
    }
   ]
  },
  {
   "title": "Sum of Message Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dataloader_message_counter_total:sum"
    }
   ]
  },
  {
   "title": "Sum of Error Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dataloader_error_counter_total:sum"
    }
   ]
  },
  {
   "title": "Slowest 10 nodes in terms of message rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk(10, rate(dataloader_message_counter_total [1h]))"
    }
   ]
  },
  {
   "title": "Top 10 nodes in terms of message error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(dataloader_error_counter_total [1h]))"
    }
   ]
  }
 ]
}